[tool.poetry]
name = "test_api"
version = "0.1.0"
description = "Test API for Keystone"
authors = [ "Alejandro Aguirre <alejandro@kainam.ai>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11.0"

# API
fastapi = "0.95.1"
uvicorn = "0.23.1"
pynest-api = "^0.1.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
